name: Kings TruckersMP Live Tracker

on:
  workflow_dispatch:

jobs:
  test-live-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

           - name: Run Kings Live Tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_MESSAGE_ID: ${{ secrets.DISCORD_MESSAGE_ID }}
        run: node tracker.js
